<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Metalama.Framework.Sdk" />
  </ItemGroup>

  <!-- Exclude the SdkExtension sample project files -->
  <ItemGroup>
    <Compile Remove="SdkExtension\**\*.cs" />
    <None Remove="SdkExtension\**\*" />
  </ItemGroup>

</Project>
