<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.15</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.23</MetalamaVersion>
    <MetalamaPremiumVersion Condition="'$(MetalamaPremiumVersion)' == ''">2026.1.23</MetalamaPremiumVersion>
    <MetalamaSamplesVersion Condition="'$(MetalamaSamplesVersion)' == ''">2026.1.23</MetalamaSamplesVersion>
    <MetalamaDocumentationReleaseVersion>2026.1.23</MetalamaDocumentationReleaseVersion>
    <MetalamaDocumentationReleaseMainVersion>2026.1.23</MetalamaDocumentationReleaseMainVersion>
  </PropertyGroup>
</Project>