// This is public domain Metalama sample code.

using Metalama.Framework.Advising;
using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using System;

namespace Doc.LAMA0651.Error;

public class CustomHashCodeAttribute : TypeAspect
{
    public override void BuildAspect( IAspectBuilder<INamedType> builder )
    {
        builder.IntroduceMethod( nameof(this.GetHashCodeTemplate), whenExists: OverrideStrategy.Override );
    }

    [Template( Name = "GetHashCode" )]
    public int GetHashCodeTemplate()
    {
        Console.WriteLine( $"Computing the hash code of {meta.Target.Type.Name}." );

        // Error: GetHashCode is generated by the C# compiler, so there is no implementation to proceed to.
        var hashCode = meta.Proceed();

        return hashCode;
    }
}
