<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Doc.Metrics.Workspaces</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Metalama.Framework.Workspaces" />
        <PackageReference Include="Metalama.Extensions.Metrics" />
    </ItemGroup>

</Project>
