<#
.SYNOPSIS
    Regenerates the table of contents and the category pages of the Errors and warnings reference.

.DESCRIPTION
    Reads every content/errors/lama####.md, groups the articles by their 'diagnostic-category' front matter
    (keys defined in Categories.psd1), sorts them by ID, and rewrites:
      - content/errors/toc.yml: Errors and warnings > category > LAMA####;
      - content/errors/errors-<key>.md: one page per non-empty category, with the table of its articles
        (using each article's 'short-description');
      - the table of categories between the GENERATED markers in content/errors/errors.md.
    Category pages of categories that no longer have articles are deleted.

    Only the coordinator of a batch runs this script. Writers never edit these files, so parallel writers
    cannot conflict.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../../../..')).Path
$articlesDir = Join-Path $repoRoot 'content/errors'
$categories = (Import-PowerShellDataFile (Join-Path $PSScriptRoot 'Categories.psd1')).Categories
$today = Get-Date -Format 'yyyy-MM-dd'
$generatedNotice = 'Generated by .claude/skills/document-diagnostics/scripts/Update-ErrorIndex.ps1. Do not edit.'

function Get-FrontMatter([string] $path) {
    $values = @{}
    $content = Get-Content $path -Raw
    if ($content -match "(?s)^﻿?---(.*?)---") {
        foreach ($line in $Matches[1] -split "\r?\n") {
            if ($line -match '^([\w-]+)\s*:\s*(.*)$') { $values[$Matches[1]] = $Matches[2].Trim().Trim('"') }
        }
    }
    return $values
}

$problems = [System.Collections.Generic.List[string]]::new()
$articles = Get-ChildItem $articlesDir -Filter 'lama*.md' | Sort-Object Name | ForEach-Object {
    $fm = Get-FrontMatter $_.FullName
    if ($fm['uid'] -ne $_.BaseName) { $problems.Add("$($_.Name): uid must be '$($_.BaseName)'.") }
    if (-not $fm['short-description']) { $problems.Add("$($_.Name): missing 'short-description' front matter.") }
    if ($categories.Key -notcontains $fm['diagnostic-category']) { $problems.Add("$($_.Name): 'diagnostic-category' must be one of: $($categories.Key -join ', ').") }
    [pscustomobject]@{ Id = $_.BaseName.ToUpperInvariant(); Uid = $_.BaseName; Description = $fm['short-description']; Category = $fm['diagnostic-category'] }
}

function New-Table($rows) {
    $sb = [System.Text.StringBuilder]::new()
    [void] $sb.AppendLine('| Article | Description |')
    [void] $sb.AppendLine('|---------|-------------|')
    foreach ($r in $rows) { [void] $sb.AppendLine("| <xref:$($r.Uid)> | $($r.Description) |") }
    return $sb.ToString().TrimEnd()
}

$toc = [System.Text.StringBuilder]::new()
[void] $toc.AppendLine("# $generatedNotice")
[void] $toc.AppendLine('items:')
[void] $toc.AppendLine('- name: Errors and warnings')
[void] $toc.AppendLine('  topicUid: errors')
[void] $toc.AppendLine('  items:')

$categoryRows = [System.Collections.Generic.List[object]]::new()
$keptPages = @()

foreach ($c in $categories) {
    $members = @($articles | Where-Object Category -EQ $c.Key)
    if (-not $members) { continue }

    $uid = "errors-$($c.Key)"
    $pageName = "$uid.md"
    $keptPages += $pageName
    $categoryRows.Add([pscustomobject]@{ Uid = $uid; Description = $c.Description })

    [void] $toc.AppendLine("    - name: $($c.Title)")
    [void] $toc.AppendLine("      topicUid: $uid")
    [void] $toc.AppendLine('      items:')
    foreach ($a in $members) {
        [void] $toc.AppendLine("        - name: $($a.Id)")
        [void] $toc.AppendLine("          topicUid: $($a.Uid)")
    }

    # Keep the creation date of an existing page.
    $pagePath = Join-Path $articlesDir $pageName
    $created = if (Test-Path $pagePath) { (Get-FrontMatter $pagePath)['created-date'] } else { $null }
    if (-not $created) { $created = $today }
    $titleLower = $c.Title.Substring(0, 1).ToLowerInvariant() + $c.Title.Substring(1)
    $page = @"
---
uid: $uid
level: 200
summary: "Reference of the $titleLower of Metalama. $($c.Description)"
keywords: "Metalama $titleLower, LAMA diagnostics, error codes, $($c.Key)"
created-date: $created
modified-date: $today
---

<!-- $generatedNotice -->

# $($c.Title)

$($c.Description)

$(New-Table $members)
"@
    $existing = if (Test-Path $pagePath) { Get-Content $pagePath -Raw } else { '' }
    # Don't touch the page (and its modified-date) when only the date would change.
    if (($existing -replace 'modified-date: .*', '').Trim() -ne ($page -replace 'modified-date: .*', '').Trim()) {
        Set-Content $pagePath $page -Encoding utf8NoBOM
    }
}

Set-Content (Join-Path $articlesDir 'toc.yml') $toc.ToString().TrimEnd() -Encoding utf8NoBOM

Get-ChildItem $articlesDir -Filter 'errors-*.md' | Where-Object { $keptPages -notcontains $_.Name } | Remove-Item

$indexPath = Join-Path $articlesDir 'errors.md'
$index = Get-Content $indexPath -Raw
$pattern = '(?s)(<!-- BEGIN GENERATED TABLE.*?-->\r?\n).*?(<!-- END GENERATED TABLE -->)'
if ($index -notmatch $pattern) { throw "errors.md has no GENERATED TABLE markers." }
$table = New-Table $categoryRows
$index = [regex]::Replace($index, $pattern, { param($m) $m.Groups[1].Value + "`n" + $table + "`n`n" + $m.Groups[2].Value })
Set-Content $indexPath $index.TrimEnd() -Encoding utf8NoBOM

Write-Host "Indexed $($articles.Count) articles in $($categoryRows.Count) categories."
foreach ($p in $problems) { Write-Host "  - $p" -ForegroundColor Yellow }
if ($problems.Count) { exit 1 }
